### PR TITLE
Using Method Constants

### PR DESCRIPTION
**Pull request by JeremyLoy**

### CODE REVIEW

**Comment by JeremyLoy** [comment]
`go vet ./...` @ Go Tip failed in travis.

Not sure why, `go vet ./...` works locally for me with Go `1.11.1`

**Comment by SamWhited** [comment]
Go vet did not fail, the tests did:

```
--- FAIL: TestTreeFindCaseInsensitivePath (0.00s)
    tree_test.go:532: Route '/u/äpfêl/' not found!
    tree_test.go:532: Route '/u/öpfêl' not found!
    tree_test.go:532: Route '/v/Äpfêl/' not found!
    tree_test.go:532: Route '/v/Öpfêl' not found!
    tree_test.go:532: Route '/w/♬' not found!
    tree_test.go:532: Route '/w/♭/' not found!
    tree_test.go:532: Route '/w/𠜎' not found!
    tree_test.go:532: Route '/w/𠜏/' not found!
    tree_test.go:541: Route '/u/äpfêl/' not found!
    tree_test.go:541: Route '/u/öpfêl' not found!
    tree_test.go:541: Route '/v/Äpfêl/' not found!
    tree_test.go:541: Route '/v/Öpfêl' not found!
    tree_test.go:541: Route '/w/♬' not found!
    tree_test.go:541: Route '/w/♭/' not found!
    tree_test.go:541: Route '/w/𠜎' not found!
    tree_test.go:541: Route '/w/𠜏/' not found!
    tree_test.go:613: Wrong result for '/u/ÄPFÊL/': got /, false; want /u/äpfêl/, true
```

**Comment by julienschmidt** [comment]
Working on it, something changed in go tip with the handling of unicode (specifically the handling of invalid unicode points)

**Comment by JeremyLoy** [comment]
ah I see. My mistake.

**Comment by SamWhited** [comment]
@julienschmidt that's likely to be golang/go@f74de24fbd94d021b047afe0dc62eddeb65ca384 if it helps

**Comment by QuLogic** [comment]
Re: test failure, see also #263.

**Pull request merged**
