### PR TITLE
Add support for HTTP 405

### PR DESCRIPTION
**Pull request by javierprovecho**
Following https://github.com/gin-gonic/gin/issues/176

### CODE REVIEW

**Comment by javierprovecho** [comment]
@julienschmidt did not see this issue https://github.com/julienschmidt/httprouter/issues/30 , would you like to I develop it too?

**Comment by julienschmidt** [comment]
Thank you Javier!

I think #30 is currently not solvable without either bad performance (trying all trees) or changing it back to to a 1-big-tree design. The latter was initially the case, but was changes to the current 1-tree-per-method design, which has often better look-up performance and is more memory efficient.

Anyways, the current code should have a small test, ensuring that the HTTP 405 support is working.

**Comment by javierprovecho** [comment]
Test added.

**Comment by julienschmidt** [comment]
Thank you!

**Comment by SuuKool** [comment]
Could someone help me with my PHP script, I'm new to github, trying to create and host a contact form, but I get a 405 Not Allowed error.

**Comment by javierprovecho** [comment]
@SuuKool welcome to GitHub, but definitely this is not the best place to ask, I suggest you to go to stackoverflow.com and ask your question there.

**Pull request merged**
