### PR TITLE
wildcard can have different parameter name based on the handler

### PR DESCRIPTION
**Pull request by UlysseM**
Hi,

I've been dealing with a case where I'd want to have different parameter name for the wildcard, depending on the handler.

Right now, it's impossible to do:
/get/:doc
/get/:user/:doc

This patch aims to make this possible, without adding any complexity when getting the route.

### CODE REVIEW

**Comment by julienschmidt** [comment]
It's against the design and makes it less efficient.

**Comment by UlysseM** [comment]
In my implementation, the tree produced by
```
/get/:doc/
/get/:user/:doc
```
is the exactly same as:
```
/get/:user/
/get/:user/:doc
```

Inside getValue, the only extra work is go inside a for loop and loop (nbrElement) times. I'm not sure this is going to have any impacts on the performances.

The only downside I see is a slightly bigger memory footprint, as the parameter name are stored inside an array for each node that have handlers.

**Comment by julienschmidt** [comment]
I appreciate your pull request (and that you are brave enough to dig into the tree code), but currently 
I am very reluctant to add anything that bloats the nodes further. Also I actually somehow intended this limitation to enforce sensible API design.
Please don't delete the fork / branch, I will reconsider it for v2.

**Comment by UlysseM** [comment]
Thank you for answering / taking a second look!

The current limitation is a bit frustrating when implementing an api like:
```
/get/view
/get/doc/rev
```
We can either do:
```
/get/doc
/get/doc/rev
```
or
```
/get/:p1
/get/:p1/:p2
```
Neither solution feel quite right, in the first, we would have  `view_id := router.Get("doc")` in our code, and in the second solution, technically the most correct, would make the code really difficult.
Not to mention we are generating an API documentation based on the same route we are passing to this router.

**Pull request closed without merging**
